# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/osx'

begin
  require 'bundler'
  Bundler.require
rescue LoadError
end

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'DevDashCam'

  app.info_plist['CFBundleIconName'] = 'AppIcon'
  app.frameworks << "Foundation"
  app.deployment_target = "12.1"
  app.xcode_dir = "/Applications/Xcode-13.2.1.app/Contents/Developer"
end
